### DISCUSSION TITLE
test 와 flyway 분리

### DISCUSSION THREAD

**Discussion by Combi153** [woowacourse-teams/2023-trip-draw#391] [기록]
test 환경에서 flyway를 사용해야 할까?

- h2 의 스키마를 형상관리할 필요가 없다고 생각
- mysql 지원 문법이 h2 가 지원하지 않는 경우 대응 어렵

현재 yml

```yaml
jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
```

flyway 사용 안하도록 변경

```yaml
jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false
```

- h2 schema 지우고 테스트를 돌림

RepositoryTest만 터진다

![스크린샷 2023-09-21 오전 2 35 36](https://github.com/woowacourse-teams/2023-trip-draw/assets/106813090/fc3873cc-cc8f-4038-8f8d-c1e45efe32f2)

RepositoryTest 에서 @DataJpaTest 를 사용하기 때문이다.

> By default, tests annotated with @DataJpaTest are transactional and roll back at the end of each test. They also use an embedded in-memory database (replacing any explicit or usually auto-configured DataSource). The @AutoConfigureTestDatabase annotation can be used to override these settings.
> 

embedded in-memory database 를 사용한다.

테스트 환경의 h2 database를 사용하지 않는 것이다. 사용하도록 변경하자.

`@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.*NONE*)`

이거 추가하면 된다.

참고자료
[Flyway를 사용하는 이유](https://jaehhh.tistory.com/119)

[H2로 SpringBoot 테스트 도중 SQL이 실행되지 않는 경우 대응법](https://kafcamus.tistory.com/45)

[Spring boot  ::  Multiple DataSource 환경에서 @DataJpaTest 이슈 정리 및 스프링 코드 분석](https://wave1994.tistory.com/181)
