### ISSUE TITLE
[feat] 세션 쿠키의 domain 값 설정

### ISSUE THREAD

**Issue by greeng00se** [woowacourse-teams/2023-trip-draw#482]
## 기능 설명
```yml
server:
  servlet:
    session:
      cookie:
        domain: tripdraw.site
```
다음과 같이 설정해서 그 도메인 아래의 페이지에서만 해당 세션 쿠키를 사용할 수 있도록 수정합니다.
